# Generated by Django 4.2.6 on 2023-10-24 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_subscription"),
    ]

    operations = [
        migrations.RemoveField(model_name="music", name="licenses",),
        migrations.RenameModel(old_name="License", new_name="UserLicense",),
        migrations.CreateModel(
            name="SongLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField()),
                (
                    "license_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.userlicense",
                    ),
                ),
                (
                    "songID",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.music"
                    ),
                ),
            ],
        ),
    ]
