# Generated by Django 4.2.6 on 2023-10-24 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_music_licenses_rename_license_userlicense_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="songlicense", unique_together={("songID", "license_type")},
        ),
    ]
