# Generated by Django 4.2.6 on 2023-10-25 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_play"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songlicense",
            name="songID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="available_licences",
                to="api.music",
            ),
        ),
    ]
