# Generated by Django 4.2.6 on 2023-10-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="context",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
